# Generated by Django 4.2.2 on 2023-06-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BroadwayData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shows_names', models.TextField(blank=True, null=True)),
                ('shows_links', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
